// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLZQY7kHGRFVuEl47mXxy9XhMe9HwN3U8',
    appId: '1:407494181657:web:19820f4363058291223b88',
    messagingSenderId: '407494181657',
    projectId: 'tuko-73f1e',
    authDomain: 'tuko-73f1e.firebaseapp.com',
    storageBucket: 'tuko-73f1e.firebasestorage.app',
    measurementId: 'G-1VV0Z14L7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_es7w2yxaUB7fPxoiN0jBKaDd_F_0uE',
    appId: '1:407494181657:android:e850a44174ab38c9223b88',
    messagingSenderId: '407494181657',
    projectId: 'tuko-73f1e',
    storageBucket: 'tuko-73f1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALCglP6S7-FKz-_58FRzSB4SrATDYN3gU',
    appId: '1:407494181657:ios:fe763b06b25054b3223b88',
    messagingSenderId: '407494181657',
    projectId: 'tuko-73f1e',
    storageBucket: 'tuko-73f1e.firebasestorage.app',
    iosBundleId: 'com.example.tukoApplication',
  );
}
